/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package org.embedded.dfs.key.value.storage.wal.api.avro.impl;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum operation {
    DELETE, PUT;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"operation\",\"namespace\":\"org.embedded.dfs.key.value.storage.wal.api.impl\",\"symbols\":[\"DELETE\",\"PUT\"]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }
}
